baseURL = "https://digitaldesa.netlify.com/"
languageCode = "en-us"
title = "Digital Desa | Upana Studio"
builddrafts = false
canonifyurls = true
contentdir = "content"
disqusShortname = "digides"
Paginate = 2
